# Generated by Django 4.0.4 on 2022-06-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='mail_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема корреспонденции'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='report_date',
            field=models.DateField(verbose_name='Отчетный период'),
        ),
    ]
