# Generated by Django 4.0.4 on 2022-06-15 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_centersprices_options_and_more'),
        ('reports', '0002_alter_reports_mail_date_alter_reports_report_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportsRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('pretrading', 'предторговый'), ('warranty', 'гарантийный')], max_length=50, verbose_name='Вид ремонта')),
                ('client', models.CharField(blank=True, max_length=150, null=True, verbose_name='Клиент')),
                ('client_phone', models.CharField(blank=True, max_length=150, null=True, verbose_name='Телефон клиента')),
                ('client_addr', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес клиента')),
                ('model_description', models.CharField(max_length=150, verbose_name='Модель продукции')),
                ('serial_number', models.CharField(max_length=30, verbose_name='Серийный номер')),
                ('report_date', models.DateField(verbose_name='Отчетный период')),
                ('buy_date', models.DateField(verbose_name='Дата покупки')),
                ('start_date', models.DateField(verbose_name='Дата начала ремонта')),
                ('end_date', models.DateField(verbose_name='Дата окончания ремонта')),
                ('parts_cost', models.IntegerField(default=0, verbose_name='За детали')),
                ('work_cost', models.IntegerField(default=0, verbose_name='За работу')),
                ('move_cost', models.IntegerField(default=0, verbose_name='За выезд')),
                ('problem_description', models.TextField(verbose_name='Описание проблемы')),
                ('work_description', models.TextField(verbose_name='Описание работ')),
                ('note', models.CharField(max_length=250, verbose_name='Примечание')),
                ('status', models.CharField(choices=[('draft', 'черновик'), ('send', 'отправлен на проверку'), ('refinement', 'возвращен на доработку'), ('received', 'получен'), ('verified', 'проверен'), ('accepted', 'принят'), ('payment', 'передан в оплату')], default='draft', max_length=100, verbose_name='Статус')),
                ('factory', models.CharField(choices=[('K', 'НОВАТЕК'), ('N', 'НОВАСИБ')], max_length=1, null=True, verbose_name='Завод-изготовитель')),
                ('main_date', models.DateField(null=True, verbose_name='Дата производства')),
                ('shift', models.CharField(max_length=1, null=True, verbose_name='Рабочая смена')),
                ('total_cost', models.IntegerField(default=0, verbose_name='Всего за ремонт')),
                ('errors', models.JSONField(default=list, verbose_name='Замечания')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.codes', verbose_name='Код неисправности')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.models', verbose_name='Модель продукции')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.mainproducts', verbose_name='Тип продукции')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reports', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ремонт',
                'verbose_name_plural': 'Ремонты',
                'ordering': ['report'],
            },
        ),
        migrations.CreateModel(
            name='ReportsParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('count', models.IntegerField(default=1, verbose_name='Количество')),
                ('document', models.CharField(max_length=250, verbose_name='Реквизиты накладной')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reportsrecords', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Деталь из ремонта',
                'verbose_name_plural': 'Детали из ремонта',
                'ordering': ['record', 'title'],
            },
        ),
    ]
