# Generated by Django 4.0.4 on 2022-06-26 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_centersprices_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0004_remove_reportsrecords_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='total_cost',
            field=models.IntegerField(default=0, verbose_name='Общая сумма по отчету'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор отчета'),
        ),
        migrations.AlterField(
            model_name='reportsrecords',
            name='code',
            field=models.ForeignKey(limit_choices_to={'is_folder': False}, on_delete=django.db.models.deletion.PROTECT, to='products.codes', verbose_name='Код неисправности'),
        ),
        migrations.AlterField(
            model_name='reportsrecords',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.models', verbose_name='Модель продукции'),
        ),
        migrations.AlterField(
            model_name='reportsrecords',
            name='model_description',
            field=models.CharField(blank=True, max_length=150, verbose_name='Модель продукции'),
        ),
        migrations.AlterField(
            model_name='reportsrecords',
            name='move_cost',
            field=models.IntegerField(blank=True, default=0, verbose_name='За выезд'),
        ),
        migrations.AlterField(
            model_name='reportsrecords',
            name='note',
            field=models.CharField(blank=True, max_length=250, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='reportsrecords',
            name='work_description',
            field=models.TextField(blank=True, verbose_name='Описание работ'),
        ),
    ]
