# Generated by Django 4.0.4 on 2022-06-26 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_reports_records_count_alter_reports_total_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reports',
            options={'ordering': ['-report_date', 'service_center', 'status'], 'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
        migrations.AlterField(
            model_name='reportsrecords',
            name='errors',
            field=models.JSONField(blank=True, default=[], verbose_name='Замечания'),
        ),
        migrations.AlterField(
            model_name='reportsrecords',
            name='factory',
            field=models.CharField(blank=True, choices=[('K', 'НОВАТЕК'), ('N', 'НОВАСИБ')], max_length=1, null=True, verbose_name='Завод-изготовитель'),
        ),
        migrations.AlterField(
            model_name='reportsrecords',
            name='main_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата производства'),
        ),
        migrations.AlterField(
            model_name='reportsrecords',
            name='parts_cost',
            field=models.FloatField(blank=True, default=0, verbose_name='За детали'),
        ),
        migrations.AlterField(
            model_name='reportsrecords',
            name='report',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reports.reports', verbose_name='Отчет'),
        ),
        migrations.AlterField(
            model_name='reportsrecords',
            name='shift',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Рабочая смена'),
        ),
        migrations.AlterField(
            model_name='reportsrecords',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'черновик'), ('send', 'отправлен на проверку'), ('refinement', 'возвращен на доработку'), ('received', 'получен'), ('verified', 'проверен'), ('accepted', 'принят'), ('payment', 'передан в оплату')], default='draft', max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='reportsrecords',
            name='total_cost',
            field=models.FloatField(blank=True, default=0, verbose_name='Всего за ремонт'),
        ),
    ]
