# Generated by Django 4.0.4 on 2022-06-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_reports_options_alter_reportsrecords_errors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsrecords',
            name='errors',
            field=models.JSONField(blank=True, default=list, verbose_name='Замечания'),
        ),
    ]
