# Generated by Django 4.0.4 on 2022-06-26 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_reportsrecords_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsrecords',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.reports', verbose_name='Отчет'),
        ),
    ]
