# Generated by Django 4.0.4 on 2022-06-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_reportsrecords_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsrecords',
            name='buy_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата покупки'),
        ),
    ]
