# Generated by Django 4.0.4 on 2022-07-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_reportsrecords_buy_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='have_fault',
            field=models.BooleanField(blank=True, default=False, verbose_name='Имеет ошибки'),
        ),
        migrations.AddField(
            model_name='reportsrecords',
            name='remarks',
            field=models.JSONField(blank=True, default=list, verbose_name='Замечания'),
        ),
        migrations.AlterField(
            model_name='reportsparts',
            name='count',
            field=models.IntegerField(null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='reportsrecords',
            name='errors',
            field=models.JSONField(blank=True, default=list, verbose_name='Ошибки'),
        ),
    ]
