# Generated by Django 4.0.4 on 2022-07-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_reports_have_fault_reportsrecords_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsrecords',
            name='errors',
            field=models.TextField(blank=True, null=True, verbose_name='Ошибки'),
        ),
        migrations.AlterField(
            model_name='reportsrecords',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Замечания'),
        ),
    ]
