# Generated by Django 4.0.4 on 2022-07-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_alter_reportsrecords_errors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportsrecords',
            name='status',
        ),
        migrations.AddField(
            model_name='reportsrecords',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Принят'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='status',
            field=models.CharField(choices=[('draft', 'черновик'), ('send', 'отправлен на проверку'), ('refinement', 'возвращен на доработку'), ('received', 'идет проверка'), ('verified', 'проверен'), ('accepted', 'принят'), ('payment', 'передан в оплату')], default='draft', max_length=100, verbose_name='Статус'),
        ),
    ]
