# Generated by Django 4.0.4 on 2022-07-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_reports_verified_count_alter_reports_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='pay_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата передачи в оплату'),
        ),
        migrations.AddField(
            model_name='reportsrecords',
            name='have_general_errors',
            field=models.BooleanField(default=False, verbose_name='Требует внимания старшего менеджера'),
        ),
    ]
