# Generated by Django 4.0.4 on 2022-08-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_reports_pay_date_reportsrecords_have_general_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsrecords',
            name='verified_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала ремонта'),
        ),
    ]
