# Generated by Django 4.0.4 on 2022-09-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_reportsrecords_verified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='total_move',
            field=models.FloatField(default=0, verbose_name='Общая сумма за выезд'),
        ),
        migrations.AddField(
            model_name='reports',
            name='total_part',
            field=models.FloatField(default=0, verbose_name='Общая сумма за детали'),
        ),
        migrations.AddField(
            model_name='reports',
            name='total_work',
            field=models.FloatField(default=0, verbose_name='Общая сумма за работы'),
        ),
        migrations.AlterField(
            model_name='reportsrecords',
            name='verified_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема записи'),
        ),
    ]
