# Generated by Django 4.0.4 on 2022-05-27 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicecentres', '0002_alter_servicecenters_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecenters',
            name='city',
            field=models.CharField(help_text='Город. Обязательное поле.', max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='servicecenters',
            name='code',
            field=models.CharField(db_index=True, help_text='Код по 1С. Обязательное поле.', max_length=50, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='servicecenters',
            name='grade',
            field=models.FloatField(default=5, editable=False, verbose_name='Рэйтинг'),
        ),
        migrations.AlterField(
            model_name='servicecenters',
            name='region',
            field=models.ForeignKey(help_text='Регион СЦ. Обязательное поле.', null=True, on_delete=django.db.models.deletion.PROTECT, to='servicecentres.serviceregions', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='servicecenters',
            name='title',
            field=models.CharField(db_index=True, help_text='Юридическое наименование. Обязательное поле.', max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='servicecontacts',
            name='service_center',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='servicecentres.servicecenters', verbose_name='Сервисный ццентр'),
        ),
    ]
