# Generated by Django 4.0.4 on 2022-05-29 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicecentres', '0003_alter_servicecenters_city_alter_servicecenters_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecontacts',
            name='service_center',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='servicecentres.servicecenters', verbose_name='Сервисный центр'),
        ),
    ]
