# Generated by Django 4.0.4 on 2022-05-30 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecentres', '0005_alter_servicecontacts_service_center'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecontacts',
            options={'ordering': ['service_center__title', 'name'], 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
    ]
