# Generated by Django 4.0.4 on 2022-06-26 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicecentres', '0006_alter_servicecontacts_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecenters',
            name='staff_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_centers', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='servicecenters',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_centers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
