# Generated by Django 4.0.4 on 2022-07-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecentres', '0007_alter_servicecenters_staff_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecenters',
            name='price_type',
            field=models.CharField(choices=[('light', 'дешевый'), ('middle', 'средний'), ('hard', 'дорогой')], default='light', max_length=100, verbose_name='Тип прайса'),
        ),
    ]
