# Generated by Django 4.0.4 on 2022-05-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_products_parent_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'Продукт'), ('2', 'Группа моделей'), ('3', 'Модель')], max_length=50, verbose_name='Категория')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
                ('object_title', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Краткое наименование')),
                ('valid_date', models.DateField(blank=True, null=True, verbose_name='Дата начала проверки производства')),
                ('guarantee_period', models.IntegerField(default=1, verbose_name='Гарантийный срок')),
                ('code_chars', models.CharField(blank=True, max_length=10, null=True, verbose_name='Буквенная кодировка')),
                ('west_id', models.IntegerField(blank=True, null=True, verbose_name='Цифровая кодировка Запад')),
                ('east_id', models.IntegerField(blank=True, null=True, verbose_name='Цифровая кодировка Восток')),
            ],
            options={
                'verbose_name': 'Продукция',
            },
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
