# Generated by Django 4.0.4 on 2022-05-30 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_myproducts_delete_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproducts',
            name='parent_product',
            field=models.ForeignKey(blank=True, limit_choices_to={'level': '1'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_prod', to='products.myproducts', verbose_name='Вид продукции'),
        ),
    ]
