# Generated by Django 4.0.4 on 2022-05-30 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_myproducts_parent_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproducts',
            name='parent_grp',
            field=models.ForeignKey(blank=True, limit_choices_to={'level': '2'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_group', to='products.myproducts', verbose_name='Группа моделей'),
        ),
    ]
