# Generated by Django 4.0.4 on 2022-05-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_myproducts_parent_grp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyProducts',
            new_name='Products',
        ),
    ]
