# Generated by Django 4.0.4 on 2022-05-30 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_myproducts_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
                ('short_title', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Краткое наименование')),
                ('valid_date', models.DateField(blank=True, null=True, verbose_name='Дата начала проверки производства')),
                ('guarantee_period', models.IntegerField(default=1, verbose_name='Гарантийный срок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
                ('code_chars', models.CharField(blank=True, max_length=10, null=True, verbose_name='Буквенная кодировка')),
                ('west_id', models.IntegerField(blank=True, null=True, verbose_name='Цифровая кодировка Запад')),
                ('east_id', models.IntegerField(blank=True, null=True, verbose_name='Цифровая кодировка Восток')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
                'ordering': ['group__product', 'group', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ModelsGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_product', to='products.mainproducts', verbose_name='Вид продукции')),
            ],
            options={
                'verbose_name': 'Группа моделей',
                'verbose_name_plural': 'Группы моделей',
                'ordering': ['product__title', 'title'],
            },
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AddField(
            model_name='models',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_group', to='products.modelsgroups', verbose_name='Группа моделей'),
        ),
    ]
