# Generated by Django 4.0.4 on 2022-05-30 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_mainproducts_models_modelsgroups_delete_products_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainproducts',
            options={'ordering': ['title'], 'verbose_name': 'Вид продукта', 'verbose_name_plural': 'Виды продуктов'},
        ),
        migrations.AlterModelOptions(
            name='models',
            options={'ordering': ['product', 'title'], 'verbose_name': 'Модель продукции', 'verbose_name_plural': 'Модели продукции'},
        ),
        migrations.RemoveField(
            model_name='models',
            name='group',
        ),
        migrations.AddField(
            model_name='models',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_product', to='products.mainproducts', verbose_name='Вид продукции'),
        ),
        migrations.DeleteModel(
            name='ModelsGroups',
        ),
    ]
