# Generated by Django 4.0.4 on 2022-05-31 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_mainproducts_options_alter_models_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainproducts',
            options={'ordering': ['title'], 'verbose_name': 'Вид продуктции', 'verbose_name_plural': 'Виды продуктции'},
        ),
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=5, unique=True, verbose_name='Код ошибки')),
                ('title', models.CharField(max_length=150, verbose_name='Описание ошибки')),
                ('repair_type', models.CharField(choices=[('easy', 'простой'), ('middle', 'средний'), ('difficult', 'сложный')], max_length=50, verbose_name='Вид ремонта')),
                ('is_folder', models.BooleanField(blank=True, default=False, verbose_name='Это группа')),
                ('parent', models.ForeignKey(limit_choices_to={'is_folder': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_code', to='products.codes', verbose_name='Группа')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_product', to='products.mainproducts', verbose_name='Вид продукции')),
            ],
            options={
                'verbose_name': 'Код неисправиности',
                'verbose_name_plural': 'Коды неисправностей',
                'ordering': ['product', 'parent__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='BasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_type', models.CharField(choices=[('easy', 'простой'), ('middle', 'средний'), ('difficult', 'сложный')], max_length=50, verbose_name='Вид ремонта')),
                ('price', models.IntegerField(default=0, verbose_name='Расценка')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_product', to='products.mainproducts', verbose_name='Вид продукции')),
            ],
            options={
                'verbose_name': 'Базовая расценка>',
                'verbose_name_plural': 'Базовые расценки',
                'ordering': ['product', 'repair_type'],
            },
        ),
    ]
