# Generated by Django 4.0.4 on 2022-05-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_baseprice_repair_type_alter_codes_is_folder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='code',
            field=models.CharField(max_length=5, verbose_name='Код ошибки'),
        ),
    ]
