# Generated by Django 4.0.4 on 2022-05-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_codes_created_at_alter_baseprice_repair_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Используется'),
        ),
        migrations.AddField(
            model_name='codes',
            name='slug',
            field=models.SlugField(default=1, max_length=5, verbose_name='Код ошибки'),
            preserve_default=False,
        ),
    ]
