# Generated by Django 4.0.4 on 2022-05-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_codes_is_active_codes_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codes',
            options={'ordering': ['product', 'code'], 'verbose_name': 'Код неисправиности', 'verbose_name_plural': 'Коды неисправностей'},
        ),
        migrations.RemoveField(
            model_name='codes',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='baseprice',
            name='repair_type',
            field=models.CharField(choices=[('none', 'не указывается'), ('document', 'выписка документов'), ('easy', 'простой'), ('middle', 'средний'), ('difficult', 'сложный'), ('very_difficult', 'очень сложный')], max_length=50, verbose_name='Вид ремонта'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='repair_type',
            field=models.CharField(choices=[('none', 'не указывается'), ('document', 'выписка документов'), ('easy', 'простой'), ('middle', 'средний'), ('difficult', 'сложный'), ('very_difficult', 'очень сложный')], max_length=50, verbose_name='Вид ремонта'),
        ),
    ]
