# Generated by Django 4.0.4 on 2022-06-01 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_codes_options_remove_codes_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codes',
            name='slug',
        ),
        migrations.AlterField(
            model_name='codes',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_folder': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_code', to='products.codes', verbose_name='Группа дефектов'),
        ),
    ]
