# Generated by Django 4.0.4 on 2022-06-03 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicecentres', '0006_alter_servicecontacts_options'),
        ('products', '0015_remove_codes_slug_alter_codes_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_product', to='products.mainproducts', verbose_name='Вид продукции'),
        ),
        migrations.CreateModel(
            name='CentersPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='Расценка')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.codes', verbose_name='Код неисправности')),
                ('service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicecentres.servicecenters', verbose_name='Сервисный центр')),
            ],
            options={
                'verbose_name': 'Базовая расценка>',
                'verbose_name_plural': 'Базовые расценки',
                'ordering': ['service_center', 'code'],
            },
        ),
    ]
