# Generated by Django 4.0.4 on 2022-06-04 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_baseprice_product_centersprices'),
    ]

    operations = [
        migrations.AddField(
            model_name='centersprices',
            name='group',
            field=models.ForeignKey(limit_choices_to={'is_folder': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.centersprices', verbose_name='Группа дефектов'),
        ),
        migrations.AddField(
            model_name='centersprices',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.mainproducts', verbose_name='Вид продукции'),
        ),
        migrations.AlterField(
            model_name='baseprice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.mainproducts', verbose_name='Вид продукции'),
        ),
    ]
