# Generated by Django 4.0.4 on 2022-06-04 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_centersprices_group_centersprices_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centersprices',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.centersprices', verbose_name='Группа дефектов'),
        ),
    ]
