# Generated by Django 4.0.4 on 2022-06-04 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_centersprices_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centersprices',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_parent_group', to='products.codes', verbose_name='Группа дефектов'),
        ),
    ]
