# Generated by Django 4.0.4 on 2022-07-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_centersprices_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproducts',
            name='check_serial',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
