# Generated by Django 4.0.4 on 2022-07-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_mainproducts_check_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseprice',
            name='price_type',
            field=models.CharField(choices=[('light', 'дешевый'), ('middle', 'средний'), ('hard', 'дорогой')], default='light', max_length=100, verbose_name='Тип прайса'),
        ),
    ]
