# Generated by Django 4.0.4 on 2022-11-09 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_baseprice_price_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время производства')),
                ('type_pk', models.IntegerField(default=0, verbose_name='PK типа продукции')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('shop', models.CharField(max_length=255, verbose_name='Производственное подразделение')),
            ],
        ),
        migrations.AlterModelOptions(
            name='baseprice',
            options={'ordering': ['product', 'price_type', 'repair_type'], 'verbose_name': 'Базовая расценка>', 'verbose_name_plural': 'Базовые расценки'},
        ),
        migrations.AlterField(
            model_name='baseprice',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Расценка должна быть больше чем ноль !')], verbose_name='Расценка'),
        ),
        migrations.AlterField(
            model_name='baseprice',
            name='repair_type',
            field=models.CharField(choices=[('none', 'не указывается'), ('document', 'выписка документов'), ('easy', 'простой'), ('middle', 'средний'), ('difficult', 'сложный'), ('very_difficult', 'очень сложный'), ('type1', 'специальный 1'), ('type2', 'специальный 2'), ('type3', 'специальный 3'), ('type4', 'специальный 4'), ('type5', 'специальный 5'), ('type6', 'специальный 6'), ('type7', 'специальный 7'), ('type8', 'специальный 8'), ('type9', 'специальный 9'), ('type10', 'специальный 10')], max_length=50, verbose_name='Вид ремонта'),
        ),
        migrations.AlterField(
            model_name='centersprices',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Расценка должна быть больше чем ноль !')], verbose_name='Расценка'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='repair_type',
            field=models.CharField(choices=[('none', 'не указывается'), ('document', 'выписка документов'), ('easy', 'простой'), ('middle', 'средний'), ('difficult', 'сложный'), ('very_difficult', 'очень сложный'), ('type1', 'специальный 1'), ('type2', 'специальный 2'), ('type3', 'специальный 3'), ('type4', 'специальный 4'), ('type5', 'специальный 5'), ('type6', 'специальный 6'), ('type7', 'специальный 7'), ('type8', 'специальный 8'), ('type9', 'специальный 9'), ('type10', 'специальный 10')], max_length=50, verbose_name='Вид ремонта'),
        ),
        migrations.AlterField(
            model_name='mainproducts',
            name='check_serial',
            field=models.BooleanField(blank=True, default=False, verbose_name='Проверять серийный номер'),
        ),
    ]
