# Generated by Django 4.0.4 on 2022-11-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_production_alter_baseprice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='production',
            options={'ordering': ['date'], 'verbose_name': 'Запись о производстве', 'verbose_name_plural': 'Записи о производстве'},
        ),
    ]
